### ISSUE TITLE
Browserify javascript

### ISSUE THREAD

**Issue by skiprox** [nycdsa/tech-action-working-group#1]
@jeremiak I was wondering if you could help me out here: I've been unable to get `browserify` to work on the javascript.

This obviously isn't the end of the world, as we can just not use `browserify` in the worst case, but would be a nice to have. I've tried the [jekyll browserify package](https://github.com/kui/jekyll-browserify) with no success.

An alternative is to ignore `js` files in the `config.yml` file and then add an `npm` script to build the `js` before deploying, but this adds another step so maybe doesn't seem like best practice. Let me know what you think.

**Comment by jeremiak** [comment]
Closing this issue since we can have CI run whatever we want and any JS scripts
